### ISSUE TITLE
chrome is open and nothing

### ISSUE THREAD

**Issue by di-iode** [DEADSEC-SECURITY/japscan-pdf-maker#1]
Hello, 

first I use a macOS, after a issus with chrome driver, I add 2 lines :
`from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager`

and changed another line, in class Mike, fonction __init__
`self.browser = webdriver.Chrome(ChromeDriverManager().install()) #start()`

Now, Programm start and chrome is open with the good page, but there is not image of manga and nothing happen.

for information I put 
`    scraper = Mike(url='https://www.japscan.ws/lecture-en-ligne/one-piece/405/')`

in the main

thank you ! :)

**Comment by DEADSEC-SECURITY** [comment]
You should use the binaries instead of using the driver manager since it causes fewer issues from my experience. 
Also, notice you will have to download the binaries from [DRIVERS](https://chromedriver.chromium.org/downloads) and put them inside the drivers directory with the name `chromedriver.exe`  or  `chromedriver` in case of linux and macOS.
Please try using the binaries to see if it fixes the issue and report to me with new information, also install a clean version of the program to prevent any of the modifications causing problems.

**Comment by di-iode** [comment]
oh sorry I try it, after see your code in selenium_starter.py ^^

But as you advise, I install a clean version of your program and add the drivers from macOS in your drivers directory.

I try 2 [drivers](https://chromedriver.storage.googleapis.com/index.html?path=96.0.4664.45/) (after unzip and name it "chromedriver") :
chromedriver_mac64.zip
and
chromedriver_mac64_m1.zip 

and always the error 
`selenium.common.exceptions.WebDriverException: Message: 'chromedrive' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

**Comment by DEADSEC-SECURITY** [comment]
There was indeed a bug with the code where it was looking for a file named `chromedrive` instead of `chromedriver`. I updated the code if you could run `git pull` to update your local repo and try again it should work

**Comment by di-iode** [comment]
Good it starts.

But now other issue : 
FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/Downloads/test_japscan-pdf-maker/japscan-pdf-maker/images/OnePiece405VF'

I confirme, not folder images (so no folder OnePiece405VF)

I will try to find why

**Comment by DEADSEC-SECURITY** [comment]
As discussed in the discord server you need to create a images folder :)
